### PR TITLE
Fix testing ci

### PR DESCRIPTION
**Pull request by rcannood**
This re-enables npm run test in the CI. It turns out that the `npm run test` currently does not succeed, so that has to be fixed separately from this PR.

## Fixed

- Re-enable npm run test in CI (#15).

### CODE REVIEW

**Comment by edmundmiller** [comment]
@rcannood Thanks! Do you want to fix the version stuff in this PR as well?

**Comment by rcannood** [comment]
> @rcannood Thanks! Do you want to fix the version stuff in this PR as well?

I don't think fixing the unit tests should be my responsibility, but I fixed them anyways :)

**Comment by edmundmiller** [comment]
> I don't think fixing the unit tests should be my responsibility, but I fixed them anyways :)

Ha, sorry, did mean to volunteer you for that! 😆 

I just meant did you mind if we creeped the scope on it, since we had no way of telling if it worked or not without fixing it.

**Review by edmundmiller — APPROVED** [review]
Looks great! Awesome fix as well, I just meant to bump the versions, not fix my duct tape tests 😆

**Pull request merged**
