### PR TITLE
Install Java within the typescript file

### PR DESCRIPTION
**Pull request by ewels**
Alternative to #174 and #175

Staying within the Typescript makes the change much much simpler. However, we lost a bunch of the functionality that comes in `actions/setup-java`.

### CODE REVIEW

**Comment by MillironX** [comment]
Ah, fun. We get the rug yanked out from under us again. :facepalm: So...I'm trying to think of ways to future-proof this to prevent future problems, as well as still maintain compatibility with old Nextflow versions.

That said, I don't think an action input is a good solution. We now have an implicit Java version underlying the action that could break next time Nextflow implements a feature that requires a more up-to-date version of Java...or in other words, the situation hasn't really changed. At best, now users can pin their Java versions and be forced to update their CI workflows manually when the Java version is required to be upgraded.

My pie-in-the-sky idea: pull the latest version of Java allowed from each Nextflow version and then install that version specifically. We could put version info into the JSON file served off the website. How you extract the versions from a Nextflow executable is still to be determined.

My more cynical approach is know that Java versions and Nextflow versions are likely to be linked, and add `setup-java` to the CI template, with appropriate version numbers picked in the Nextflow version matrix.

**Comment by ewels** [comment]
Not really rug pulling - the Java 11 removal has been coming for a while and it's super old, it reached end of life already in October. GitHub will be removing it from their base images in a few weeks, we're just slightly unlucky with timings that they didn't do it back in October when they should have done. Then we would have never noticed.

I'm increasingly unhappy with my attempts at fixing this during today. I thought it would be quite simple to run the `setup-java` step inside this action to resolve all the issues but it's really not gone like that.

If I can get this PR to work, my suggestion is:

* We release v2.1 with this step in it to unblock the failing CI jobs that are currently happening everywhere without folks needing to do emergency patches on their pipelines
* We revert the change and release v3.0 basically as it was before, but with an updated readme telling people to run `setup-java` before calling this action
    * If they don't then it should still work after mid-January when GitHub updates anyway
    * It maintains a separation of concerns and keeps this action with a narrow scope
    * It's probably good that people have explicit control of this part of their environment
* We update the nf-core template to use `@v3` and `setup-java` and people will progressively update to this in a non-breaking-change manner with template updates.

Separately, I'm also working with the Nextflow team to see if we can get nightly builds of Nextflow to do a small number of canary tests with. That should help give advance warning of this kind of thing, whilst allowing us to continue testing pipelines with edge releases to catch pipeline-specific edge cases before stable releases.

What do you think @MillironX ?

**Comment by MillironX** [comment]
Sounds good to me. I'm satisfied with doing a patch to get things running and then a longer-term solution for later. I will try to get something working tonight.

**Comment by ewels** [comment]
ok, I might give up, go to bed and and hand over to you @MillironX 

I feel like I'm close in this PR, but it's not updating the default version of Java for some reason: `java -version` is still printing OpenJDK 11 instead of Zulu 17.

The logic here is basically the same as `setup-java`, see [this code](https://github.com/actions/setup-java/blob/8df1039502a15bceb9433410b1a100fbe190c53b/src/distributions/base-installer.ts#L164-L175):

```ts
  protected setJavaDefault(version: string, toolPath: string) {
    const majorVersion = version.split('.')[0];
    core.exportVariable('JAVA_HOME', toolPath);
    core.addPath(path.join(toolPath, 'bin'));
    core.exportVariable(
      `JAVA_HOME_${majorVersion}_${this.architecture.toUpperCase()}`,
      toolPath
    );
  }
```

So I'm not quite sure what I'm doing wrong. Maybe something to do with subshells in the same script execution not being updated? Or maybe something simpler.

Keen to see what you make of it! Feel free to continue pushing commits to this branch as you like.

**Comment by MillironX** [comment]
Closing as #177 already resolved this

**Pull request closed without merging**
