### PR TITLE
Switch out the API

### PR DESCRIPTION
**Pull request by MillironX**
Well, here it is: [the big rewrite](https://youtu.be/xCGu5Z_vaps). I don't want this merged yet, but want it to be available for everyone to be testing against. Please try some of your biggest and baddest testing workflows against this branch (I've committed the sin of committing the build to the branch so we can do that).

```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index d44aa34..48b4c4c 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,7 +45,7 @@ jobs:
         uses: actions/checkout@v4

       - name: Install Nextflow
-        uses: nf-core/setup-nextflow@v1
+        uses: MillironX/setup-nextflow@feature/api-switch
         with:
           version: "${{ matrix.NXF_VER }}"
```

This is a breaking change, so I want to properly deprecate the unused parameters on v1 today, then move this to v2 once it's properly tested.

### CODE REVIEW

**Comment by MillironX** [comment]
Things that I want to see before merging this PR:

- [x] Confirmation of a successful stress-test from someone at @nf-core/modules 
- [ ] Confirmation of a successful stress-test from someone at @nf-core/sarek 

I have personally stress-tested this PR on [taxprofiler](https://github.com/nf-core/taxprofiler), since that pipeline is near and dear to me. I want someone else (who doesn't have a conflict of interest) to do their best to break it on some of our most problematic repos, though. Hopefully we can get this version into the template before the hackathon!

**Comment by mashehu** [comment]
For modules, I just kicked off this one again: https://github.com/nf-core/modules/pull/4726/checks, might be a good candidate

**Comment by MillironX** [comment]
> For modules, I just kicked off this one again: [nf-core/modules#4726 (checks)](https://github.com/nf-core/modules/pull/4726/checks), might be a good candidate

That one is still pointed at `nf-core/setup-nextflow@v1`. In order to test the new API, submit a pull request with `MillironX/setup-nextflow@feature/api-switch`. Just mark it as draft or something along those lines to make sure it doesn't get merged.

**Comment by mashehu** [comment]
Looking good for now: https://github.com/nf-core/modules/actions/runs/7845940111/job/21411506756

**Comment by MillironX** [comment]
All right, I'm giving @nf-core/sarek team one week before I merge and tag this. Otherwise I won't have time to get the pipeline template updated before the hackathon. Have fun!

**Review by MatthiasZepper — APPROVED** [review]
Excellent work! Thanks a lot!

Minor remark: When I ran `npm audit` (v21.6.1/npm v10.2.4), it warned me about several security vulnerabilities in the dependencies, [including a highly critical one in the JSON parsing](https://github.com/advisories/GHSA-9c47-m6qq-7p4h). Although we trust the API in that case, I think it can't harm to run an `npm audit fix` and commit the updated `package-lock.json`.

**Pull request merged**
