### PR TITLE
Separate API calls from install logic

### PR DESCRIPTION
**Pull request by MillironX**
## Background

This is phase two of my four-part plan to fix the gripes with this action

- [x] Add code coverage metrics (so we know where we came from)
- [x] Separate API calls from install logic (cleanly separating these should _greatly_ simplify the required fixes for #7, #19, #24)
- [ ] _Aside:_ apply the fixes
- [ ] Address #22 (now that we have a clean code base, we can build upon it)

### Separate API calls from install logic 

Merry Christmas, nf-core team! Here is a major overhaul to the action code, which will allow us to add mocks, create unit tests, and potentially even substitute caches or external APIs when the GitHub API hits a rate limit. I might want to add a few more tests before merging, but would love feedback now.

### CODE REVIEW

**Comment by MillironX** [comment]
Hey, @edmundmiller. Everything is ready to go, except for the filename lint rules. I can't find what these rules are, or where they come from. Could you point me in the right direction, and then I can fix that?

**Comment by mashehu** [comment]
> Hey, @edmundmiller. Everything is ready to go, except for the filename lint rules. I can't find what these rules are, or where they come from. Could you point me in the right direction, and then I can fix that?

These linting rules are quite hidden: the culprit was this one: https://github.com/github/eslint-plugin-github/blob/main/lib/configs/recommended.js#L21

**Review by edmundmiller — APPROVED** [review]
Awesome work!

I'm wondering if there's any way we can "sniff" the number of API requests in the tests? If there's not a quick resolution let's just make a follow up issue.

**Comment by mashehu** [comment]
You can read the rate limit in the response header under `x-ratelimit-remaining`

**Comment by MatthiasZepper** [comment]
> You can read the rate limit in the response header under `x-ratelimit-remaining`

[Or avoid reinventing the wheel](https://github.com/MatthiasZepper/gh-api-confine) :-)

**Comment by edmundmiller** [comment]
@MatthiasZepper where have you been hiding that???

But I was actually talking about in this code base to see how many we're using and then do a back of the napkin calculation.

**Comment by MillironX** [comment]
> I'm wondering if there's any way we can "sniff" the number of API requests in the tests?

Not sure why? 😕 There are exactly ~~three~~five API calls made by the test suite now: all other "API" tests now use static objects.

**Comment by edmundmiller** [comment]
> Not sure why? 😕 There are exactly threefive API calls made by the test suite now: all other "API" tests now use static objects.

To make sure we don't introduce any regressions because it's been a huge pain during hackathons and for Sarek, and we're about to push it to the limit with [the scatter CI in methylseq](https://github.com/nf-core/methylseq/pull/350) that I hope to add to the template.

**Comment by MatthiasZepper** [comment]
> @MatthiasZepper where have you been hiding that???

In plain sight, obviously. [Bragged about it a lot](https://nfcore.slack.com/archives/CE5LG7WMB/p1697297280327709) - so often that I already felt bad about it. 

Regarding scatter: Just mind that the billable minute are calculated per job level. As far as I know, the nf-core organization doesn't have to pay for the Actions' runtime, but should GitHub ever change its pricing model, we need to be careful as separating everything into nano-jobs will have a great impact then.

**Comment by MillironX** [comment]
> To make sure we don't introduce any regressions

Regressions in what, exactly? You're worried that the action is going to today use, say 5 API calls, and then we might break it by introducing a bug that uses, say 10 API calls?

> because it's been a huge pain during hackathons and for Sarek...

I get that, but that's during unit testing of _pipelines_, not of _this action_, right? So in that case, trying to find out the timeouts beforehand would happen exactly as we've talked about in #19, and we can add timeout and cooldown abilities to OctokitWrapper easily now.

**Comment by edmundmiller** [comment]
> Regarding scatter

Yeah I think we're going to have to cross that bridge if they change the pricing model.

I'm not following though, you're saying if they charge per job? I think the math would come out pretty close, the tests are taking 1-2 minutes a piece. 

The way it's broken up, we could shard them into 4 sets as well, instead of 20 jobs. That could be a better idea anyway because we'll start saturating the free runners quickly.

**Comment by edmundmiller** [comment]
> Regressions in what, exactly? You're worried that the action is going to today use, say 5 API calls, and then we might break it by introducing a bug that uses, say 10 API calls?

Exactly!

Anyway it was just a wish list item, I made #30 if we ever get time/motivation to follow up so good to merge with me @MillironX !

**Comment by MatthiasZepper** [comment]
Firstly, sorry @MillironX for hijacking the discussion on your PR. I am neutral and will not submit a review on this PR, since I not even remotely understand all the consideration that went into it. 

> I'm not following though, you're saying if they charge per job? I think the math would come out pretty close, the tests are taking 1-2 minutes a piece.

[I was referring to this section from the HowTo article on Token rotation from Shopify](https://shopify.engineering/automatically-rotate-github-tokens):

> _Our original cost estimates included certain calculation assumptions and misconceptions that ended up not holding true in production._
> 
> _The first assumption was mostly due to a lack of research: the granularity of what GitHub refers to as “[billable minutes](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates)”. Understanding that the granularity of a billable minute is at, well, the minute-level was one thing; the other thing was the way that the rounding and bucketing works._ 
> 
> _Billable minute calculations are not performed at an organization level, but rather at the job level. Each workflow has N underlying jobs, and each underlying job has an execution duration that is rounded to the nearest minute. These rounded nearest minutes are then summed together–even if the jobs were run in parallel–and billed to the organization. Because of this, workflows that ran 10 parallel jobs that would execute in 1 second each would end up accruing 10 billable minutes._
> 
> _These miscalculations ended up exploding our costs during our prototyping phase and led to an architecture refactoring to sequentially executing all downstream workflows in a single job._

**Pull request merged**
